CATALOGUE_HOST: catalogue.backend-{{ env }}.ecommercial.store
USER_HOST: user.backend-{{ env }}.ecommercial.store
CART_HOST: cart.backend-{{ env }}.ecommercial.store
SHIPPING_HOST: shipping.backend-{{ env }}.ecommercial.store
PAYMENT_HOST: payment.backend-{{ env }}.ecommercial.store